# Generated by Django 4.0.4 on 2022-04-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='variant',
            fields=[
                ('local_id', models.CharField(max_length=200, null=True)),
                ('linking_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('reference_sequence', models.CharField(max_length=200)),
                ('hgvs', models.CharField(max_length=200)),
            ],
        ),
    ]
